# Change these first
owner: porrale # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - porrale

sites:
  - name: Google
    url: https://www.google.com
  - name: Notariar
    url: https://notariar.com.ar
  - name: TFM IT Solutions
    url: https://tfmit.com
  - name: PrivilegedBA
    url: https://privilegedba.com.ar
  - name: Escuela 8
    url: https://portaleducativoes8pilar.com.ar
  - name: Villegas Pasteleria  
    url: https://andreavillegasapp.com
  - name: Madero Parking
    url: https://maderoparking.com
  - name: ORD Agencias
    url: https://ordagencias.com.ar
  - name: Agencias TFM - Gestion de loterias
    url: https://agenciastfm.com.ar
  - name: MCN Encomiendas
    url: https://mcnencomiendas.com.ar
    



    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: /status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
